Bài 7:Các hàm thống kê trên Tensor

In [3]:
import torch
a=torch.rand(3,4)
print(a)
print("\nMean:")
#Mean là giá trị trung bình
print(torch.mean(a, dim=0))
#Độ lệch chuẩn
print("\nStandard deviation:")
print(torch.std(a, dim=0))
#Tính tổng
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))
#Còn dim=0 là theo chiều Trên xuống dưới, dim=1 là theo chiều trái sang phải, dim=2 là chỉ có khi 3 chiều
print(torch.mean(a, dim=1))
print(torch.std(a, dim=1))
print(torch.cumsum(a, dim=1))

tensor([[0.7526, 0.6968, 0.9876, 0.4987],
        [0.3365, 0.1598, 0.6995, 0.5490],
        [0.3076, 0.7918, 0.7060, 0.6764]])

Mean:
tensor([0.4656, 0.5495, 0.7977, 0.5747])

Standard deviation:
tensor([0.2490, 0.3408, 0.1645, 0.0916])

Cumulative sum:
tensor([[0.7526, 0.6968, 0.9876, 0.4987],
        [1.0891, 0.8566, 1.6870, 1.0477],
        [1.3967, 1.6484, 2.3930, 1.7241]])
tensor([0.7339, 0.4362, 0.6204])
tensor([0.2012, 0.2369, 0.2142])
tensor([[0.7526, 1.4494, 2.4369, 2.9356],
        [0.3365, 0.4963, 1.1958, 1.7448],
        [0.3076, 1.0994, 1.8054, 2.4817]])


In [ ]:
Yêu cầu: Thử thay dim 0=1