Bài 2:Tạo các Tensor thường dùng

In [2]:
import torch
#Tạo tensor ngẫu nhiên với 3 hàng và 4 cột
#rand không tạo ra số âm nhưng randn có thể
a=torch.rand(3,4)
e=torch.randn(3,4)
#Tạo tensor với giá trị 0 với 2 hàng và 3 cột
b=torch.zeros(2,3)
#Tạo tensor với giá trị 1 với 2 hàng và 3 cột
c=torch.ones(2,3)
#Tạo tensor là ma trận đơn vị với 3 hàng và 3 cột
d=torch.eye(3,3)
f=torch.full((5,5),10)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

tensor([[0.1844, 0.8469, 0.4609, 0.6830],
        [0.7178, 0.6476, 0.2393, 0.8770],
        [0.0678, 0.9868, 0.0770, 0.6333]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[-0.4126, -0.1793, -0.9663, -1.4832],
        [-1.0071, -0.2379, -0.0387,  0.4636],
        [ 1.1074,  3.0824,  1.2420, -1.0489]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


Với a và e là tạo tensor ngẫu nhiên với kích thước được cho trong ngoặc.Trong đó a không thể tạo ra số âm nhưng e có thể.Zeros và ones là tạo với giá trị toàn 0 và 1. Còn eye là ma trận đơn vị.