Bài 5:Flatten và Reshape

In [1]:
import torch
a=torch.randn(3,4)
print("Tensor:")
print(a)
print("Số phần tử trước khi reshape:",a.numel())
#ravel là biến các tensor thành 1 chiều 
print("Flatten(Làm phẳng:)")
print(a.ravel())
print("Reshape")
#Biến đổi kích cỡ mà không cần tạo lại
print(a.reshape(3,2,2))
print("Số phần từ sau khi reshape:",a.numel())
print("Đổi thành 2x6:")
print(a.reshape(2,6))


Tensor:
tensor([[-0.7574,  0.7573,  0.2372, -1.7400],
        [-0.7681,  0.9748, -0.0172,  0.2437],
        [-0.1228,  0.4378,  2.0127, -0.1987]])
Số phần tử trước khi reshape: 12
Flatten(Làm phẳng:)
tensor([-0.7574,  0.7573,  0.2372, -1.7400, -0.7681,  0.9748, -0.0172,  0.2437,
        -0.1228,  0.4378,  2.0127, -0.1987])
Reshape
tensor([[[-0.7574,  0.7573],
         [ 0.2372, -1.7400]],

        [[-0.7681,  0.9748],
         [-0.0172,  0.2437]],

        [[-0.1228,  0.4378],
         [ 2.0127, -0.1987]]])
Số phần từ sau khi reshape: 12
Đổi thành 2x6:
tensor([[-0.7574,  0.7573,  0.2372, -1.7400, -0.7681,  0.9748],
        [-0.0172,  0.2437, -0.1228,  0.4378,  2.0127, -0.1987]])


Yêu cầu:
• Kiểm tra số phần tử trước và sau khi reshape.
=> Số phần tử trước và sau khi rephase là như nhau
• Thử reshape Tensor thành kích thước 2 × 6.