Bài 2:Tạo các Tensor thường dùng

In [1]:
import torch
#Tạo tensor ngẫu nhiên với 3 hàng và 4 cột
#rand không tạo ra số âm nhưng randn có thể
a=torch.rand(3,4)
e=torch.randn(3,4)
#Tạo tensor với giá trị 0 với 2 hàng và 3 cột
b=torch.zeros(2,3)
#Tạo tensor với giá trị 1 với 2 hàng và 3 cột
c=torch.ones(2,3)
#Tạo tensor là ma trận đơn vị với 3 hàng và 3 cột
d=torch.eye(3,3)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.6367, 0.0805, 0.4316, 0.6991],
        [0.4375, 0.8577, 0.6541, 0.6463],
        [0.7774, 0.8258, 0.2256, 0.0429]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[ 0.9923,  0.7825, -0.6362, -1.3569],
        [-0.2945,  1.1517, -0.2699,  2.1303],
        [ 1.5694,  0.4754, -1.5702,  0.5007]])


Với a và e là tạo tensor ngẫu nhiên với kích thước được cho trong ngoặc.Trong đó a không thể tạo ra số âm nhưng e có thể.Zeros và ones là tạo với giá trị toàn 0 và 1. Còn eye là ma trận đơn vị.