Bài 4:Slicing và Index

In [ ]:
import torch
a=torch.randn(3,4,5)
print("Tensor:")
print(a)
#Slicing a[1]: là in cá giá trị của khối 1,Tensor trên có 3 khối 0,1,2 a[1] là in giá trị của khối 1
print("Tensor a[1]:")
print(a[1])
#Index bao gồm a[x1:y1, x2:y2, x3:y3]
#Trong đó x1:y1 nghĩa là chọn khối để in ví dụ 1:2 là in khối 1->2 còn trong bài 1: nghĩa là in khối từ 1 tới hết
#x2:y2 là chọn hàng để in khi 2:4 tức là in hàng 2,3
#x3:y3 là chọn cột để in
print("Tensor a[1:,2:4]")
#Khi in ra sẽ có 2 khối do chọn khối in từ 1 tới hết và mỗi khối chỉ hiển thị hàng 2,3 của khối đó
print(a[1:,2:4])
print("Hai phần từ cuối của chiều thứ 3:")
print(a[:, :,3:5])

Tensor:
tensor([[[ 1.3130, -1.3224,  0.6201, -0.7211, -1.4183],
         [-0.2000, -0.5991,  1.1973,  1.3697,  1.5240],
         [-0.7852,  1.3079,  1.0915,  1.2374,  0.4984],
         [ 0.1390,  1.7582,  0.9977, -0.3343, -0.6020]],

        [[ 2.1181,  0.5066,  1.6667,  0.9058,  0.2651],
         [-1.1757, -0.8933,  0.7725, -1.1356, -0.1816],
         [-0.3601, -0.0875, -0.2936,  0.6996,  0.3378],
         [-0.1685,  0.3923, -0.7201, -1.9025,  0.7328]],

        [[ 0.7039,  0.6258,  0.5357,  0.9751, -0.8376],
         [ 0.5393, -0.2759, -0.8450, -1.0737, -0.2150],
         [ 0.8661,  1.0117,  0.2259,  0.2463, -2.6808],
         [ 0.0437,  1.4827, -0.6166,  1.5667, -0.4398]]])
Tensor a[1]:
tensor([[ 2.1181,  0.5066,  1.6667,  0.9058,  0.2651],
        [-1.1757, -0.8933,  0.7725, -1.1356, -0.1816],
        [-0.3601, -0.0875, -0.2936,  0.6996,  0.3378],
        [-0.1685,  0.3923, -0.7201, -1.9025,  0.7328]])
Tensor a[1:,2:4]
tensor([[[-0.3601, -0.0875, -0.2936,  0.6996,  0.3378],
       

Yêu cầu:Cho biết shape của a[1] và a[1:, 2:4]. Thử lấy hai phần tử cuối cùng trên chiều thứ ba.



> `a[1]` là in các giá trị của khối 1. Tensor trên có 3 khối với index 0, 1, 2, nên `a[1]` là in giá trị của khối có index 1. Cú pháp slicing có dạng `a[x1:y1, x2:y2, x3:y3]`. Trong đó, `x1:y1` dùng để chọn khối cần in; ví dụ `1:2` là chọn khối có index 1, còn `1:` nghĩa là chọn khối từ index 1 đến hết. `x2:y2` dùng để chọn hàng, ví dụ `2:4` nghĩa là chọn hàng có index 2 và 3. `x3:y3` dùng để chọn cột. Khi sử dụng `a[1:, 2:4]`, kết quả sẽ có 2 khối vì chọn các khối từ index 1 đến hết, và trong mỗi khối chỉ hiển thị hàng có index 2 và 3.
